---
# SPDX-FileCopyrightText: 2025 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

# Verifies action/workflow calls are pinned to SHA commit values
name: '📌 Audit GitHub Actions'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths: ['.github/**']

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  verify:
    name: 'Check SHA pinned actions'
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-verify-github-actions.yaml@8c3cf221da0e47955647647c9a254c1f807081ce  # v0.2.18
    permissions:
      contents: read
